
stages:
  - check
  - build
  - release

# Run this pipeline only for new tags
workflow:
  rules:
    - if: '$CI_COMMIT_TAG'

check-job:
  image: nimlang/nim:2.0.4-alpine-onbuild
  stage: check
  script:
    - nimble refresh
    - nimble check

build-job:
  image: nimlang/nim:2.0.4-alpine-onbuild
  stage: build
  script:
    - echo "Compiling the code..."
    - nimble build -d:ssl -d:release

release-job:
  stage: release
  script:
    - git config --global user.email "ci@example.com"
    - git config --global user.name "CI/CD Pipeline"
    - git remote set-url origin https://gitlab.com/your-username/your-repo.git
    - git fetch origin
    - git checkout trunk
    - git merge --ff-only $CI_COMMIT_TAG
    - final_tag=${CI_COMMIT_TAG%-rc}
    - git tag $final_tag
    - git push origin trunk
    - git push origin $final_tag
  only:
    - tags
  dependencies:
    - build-job
